name: EvoDragons
version: '${project.version}'
main: me.syntaxerror.evodragons.EvoDragons
api-version: '1.16'
commands:
  evodragons:
    description: all commands related to EvoDragons
    usage: "/evodragons [reload, loot]"